<?php

namespace Tests\Feature\Service;

use App\Services\LineBotService;
use Tests\TestCase;

class LineBotServiceTest extends TestCase
{
    /** @var LineBotService */
    private $lineBotService;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->lineBotService = app(LineBotService::class);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testPushMessage(){
        $response = $this->lineBotService->pushMessage('僕は悪いスライムじゃないよ！！');
        #$this->assertJson(200, $response->getHTTPStatus());
        #$this->assertEquals(200, $response->getHTTPStatus());
    }

}

